#' Example dataset: winddata
#'
#' Data with windspeed data forecast from 28.08.25 (hgtprs)
#'
#' Is a dataframe generated by get_data
#' @source https://nomads.ncep.noaa.gov/dods/gefs/gefs20250828/gefs_pgrb2ap5_all_00z.ascii?hgtprs[0:30][0:64][2][282][28]
#' @examples
#' data("winddata", package = "Enclust")
#' head(winddata)
"winddata"
